POST http://localhost:3001/auth/password-reset
X-CSRF-TOKEN: TuYhXuqO-LfqBc6lD-i_cOVXINcWO06esOQ4
Content-Type: application/json

{
  "passwordResetToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoicGFzc3dvcmRSZXNldFRva2VuIiwidXNlcklkIjozLCJpYXQiOjE2NTM3NzE0NTcsImV4cCI6MTY2OTMyMzQ1N30.huFQhwNcnDHrIf0fUPtyrxt9l6KxlTCwQ1zdyemB66A",
  "password": "asia_ei_kunnossa"
}